services:
  postgres:
    image: postgres:17.2-alpine3.20
    container_name: postgres
    hostname: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: peerlink
      POSTGRES_PASSWORD: peerlink9999
    ports:
      - "8081:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    hostname: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@korayabi.com
      PGADMIN_DEFAULT_PASSWORD: peerlink9999
    ports:
      - "8082:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.0
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=changeme
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - peerlink
    ports:
      - "8083:9200"
      - "9300:9300"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
      - elastic_logs:/usr/share/elasticsearch/logs

  kibana:
    image: docker.elastic.co/kibana/kibana:8.16.0
    container_name: kibana
    hostname: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTIC_PASSWORD=changeme
    networks:
      - peerlink
    ports:
      - "8084:5601"
    volumes:
      - kibana_data:/usr/share/kibana/data
    depends_on:
      - elasticsearch

networks:
  peerlink:
    driver: bridge

volumes:
  db_data:
  pgadmin_data:
  elastic_data:
  elastic_logs:
  kibana_data:
