# Generated by Django 5.1.4 on 2024-12-20 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peerlink_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torrent',
            name='uploaded_by',
        ),
        migrations.DeleteModel(
            name='Download',
        ),
        migrations.DeleteModel(
            name='Torrent',
        ),
    ]
