# Generated by Django 5.1.4 on 2025-02-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerlink_service', '0003_alter_group_id_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='aes_key',
            field=models.CharField(blank=True, editable=False, max_length=32),
        ),
    ]
