# Generated by Django 5.1.4 on 2025-02-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerlink_service', '0004_access_aes_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='aes_key',
            field=models.CharField(blank=True, default='00000000000000000000000000000000', editable=False, max_length=32),
        ),
    ]
