# Generated by Django 5.1.4 on 2025-03-02 11:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerlink_service', '0006_remove_access_aes_key_group_aes_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shared',
            fields=[
                ('file_hash', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('file_name', models.CharField(editable=False, max_length=256)),
                ('currently_sharing_users', models.ManyToManyField(related_name='currently_sharing_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
