# Generated by Django 5.1.4 on 2025-04-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerlink_service', '0007_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='shared',
            name='magnetLink',
            field=models.CharField(default='', editable=False, max_length=256),
            preserve_default=False,
        ),
    ]
