# Generated by Django 5.1.4 on 2025-04-20 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peerlink_service', '0008_shared_magnetlink'),
        ('peerlink_service', '0009_user_photo'),
    ]

    operations = [
    ]
