# Generated by Django 5.1.4 on 2025-04-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerlink_service', '0010_merge_0008_shared_magnetlink_0009_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(editable=False, max_length=512)),
                ('file_hash', models.CharField(editable=False, max_length=64)),
            ],
        ),
    ]
